name: wisata_candi
description: A new Flutter project.

publish_to: 'none' 



environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - images/


  